AWSTemplateFormatVersion: '2010-09-09'

Description: Main stack that orchestrates VPC and Application stacks

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name for resource tagging
  
  DRSTargetRegion:
    Type: String
    Description: Enter the AWS Region for DRS agent installation (e.g., us-east-1)
    Default: us-east-1
    AllowedPattern: ^[a-z][a-z]-[a-z]+-[0-9]+$
    ConstraintDescription: Must be a valid AWS region name (e.g., us-east-1)

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-edr-replication-test.s3.ap-south-1.amazonaws.com/vpc-stack.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: 192.168.0.0/16
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-vpc
        - Key: Environment
          Value: !Ref EnvironmentName

  ApplicationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://aws-edr-replication-test.s3.ap-south-1.amazonaws.com/app-stack.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        EnvironmentName: !Ref EnvironmentName
        DRSTargetRegion: !Ref DRSTargetRegion
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-app
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  VpcId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcId
    Export:
      Name: !Sub ${AWS::StackName}-VpcId

  AppServerIP:
    Description: Application Server Private IP
    Value: !GetAtt ApplicationStack.Outputs.AppServerIP
    Export:
      Name: !Sub ${AWS::StackName}-AppServerIP

  DBServerIP:
    Description: Database Server Private IP
    Value: !GetAtt ApplicationStack.Outputs.DBServerIP
    Export:
      Name: !Sub ${AWS::StackName}-DBServerIP

